### ISSUE TITLE
Does not parse a table with an array of tables

### ISSUE THREAD

**Issue by tobia** [yosymfony/toml#12]
This should be valid syntax, if I'm reading the specs correctly:

    [fruit]
    name = "apple"

    [[fruit.variety]]
    name = "red delicious"

    [[fruit.variety]]
    name = "granny smith"

and should produce the following (in JSON):

    {
        "fruit": {
            "name": "apple",
            "variety": [
                {"name": "red delicious"},
                {"name": "granny smith"}
            ]
        }
    }

But right now this parser returns an error: 

`Yosymfony\Toml\Exception\ParseException with message 'Syntax error: the table fruit.variety has already been defined in "test.toml" at line 6 (near "]")'`

By the way, it should also work without the initial section:

    [[fruit.variety]]
    name = "red delicious"

    [[fruit.variety]]
    name = "granny smith"

in which case it should give the same JSON as above, without the `"name": "apple"` line.

**Comment by malc0mn** [comment]
I'm not sure about your claim, since I read this (in the docs here https://github.com/toml-lang/toml):

`You cannot define any key or table more than once. Doing so is invalid.

# DO NOT DO THIS

[a]
b = 1

[a]
c = 2
# DO NOT DO THIS EITHER

[a]
b = 1

[a.b]
c = 2`

**Comment by yosymfony** [comment]
This bug has been fixed in master branch.
