### ISSUE TITLE
Inline sub-tables don't work

### ISSUE THREAD

**Issue by tobia** [yosymfony/toml#13]
An inline sub-table:

    [tab1]
    key1 = {name='Donald Duck'}

should be parsed like this:

    [
        "tab1" => [
            "key1" => [
                "name" => "Donald Duck",
            ],
        ],
    ]

instead, it currently becomes this:

    [
        "tab1" => [],
        "key1" => [
            "name" => "Donald Duck",
        ],
    ]

**Comment by yosymfony** [comment]
Thanks for reporting it
