### ISSUE TITLE
How can I save a array config to a toml file?

### ISSUE THREAD

**Issue by lineofsky2017** [yosymfony/toml#20]
I want to save some additional variables to my config file for program next running, but I don't know how to do it, I haven't found in your documentation. Does it hava this function?

**Comment by yosymfony** [comment]
At this moment `TomlBuilder` does not support arrays. So you could write an iterator to process each value of your array.

**Comment by betrixed** [comment]
I haven't used TomlBuilder. But I just scanned its source code, and it looks sensible, in that the **addValue** method for (string $key, $value,$comment=null) supports nested arrays as a value, as long as content values all the same type, by calling method dumpValue , dumpArray, and recursive call to dumpValue.

**Comment by yosymfony** [comment]
Sorry @lineofsky2017, I made a mistake in my previous comment. The method `addValue` has support for arrays
