### ISSUE TITLE
Toml::parse() throws exception on Windows when a string is used.

### ISSUE THREAD

**Issue by Zerzera** [yosymfony/toml#27]
When i try to parse a string i get an exception that the path limit has been reached.
` \Exception\ErrorException (E_WARNING) is_file(): File name is longer than the maximum allowed path length on this platform (260):`

Which makes sense, because i'm not trying to open a file.

![image](https://user-images.githubusercontent.com/12538/47500936-74a37a00-d864-11e8-9059-1a2d4a9d8712.png)

**Comment by yosymfony** [comment]
You are using an out-of-date version, so please, update to latest

**Comment by Zerzera** [comment]
Thanks for your response.
Will take a look into updating php 😄 

` yosymfony/toml v1.0.4 requires php >=7.1 -> your PHP version (7.0.31) does not satisfy that requirement.`
