### ISSUE TITLE
Only double-quoted strings work in arrays, contrary to spec

### ISSUE THREAD

**Issue by L-Clouds** [yosymfony/Toml#9]
The 0.4 spec gives the following as an example:

arr4 = [ "all", 'strings', """are the same""", '''type'''] # this is ok

Using this library, it errors:

Fatal error: Uncaught exception 'Yosymfony\Toml\Exception\ParseException' with message 'Syntax error in "test.toml" at line 0 (near "'")' in Yosymfony\Toml\Parser.php:468 Stack trace: #0 Yosymfony\Toml\Parser.php(373): Yosymfony\Toml\Parser->getArrayValue() #1 Yosymfony\Toml\Parser.php(60): Yosymfony\Toml\Parser->processKeyValue() #2 Yosymfony\Toml\Toml.php(55): Yosymfony\Toml\Parser->parse('arr4 = [ "all",...') #3 Testing.php(22): Yosymfony\Toml\Toml::parse('test.toml') #4 {main} thrown in Yosymfony\Toml\Parser.php on line 468

The only non-erroring string form in an array is "string".  Errors are produced with 'string', '''string''', or """string""", regardless whether mixed or all the same for the array contents.

**Comment by yosymfony** [comment]
Fixed and a new release ready. Thank you.
